import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Importing Poppins font
import ReactQueryProvider from "./utils/ReactQueryProvider";
import "./globals.css";

const poppins = Poppins({ weight: "400", subsets: ["latin"] }); // Using Poppins font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReactQueryProvider>
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
